"""Initialization

Revision ID: 72910f01539a
Revises: 
Create Date: 2026-02-23 10:41:55.641331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72910f01539a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('two_factor_secret', sa.Text(), nullable=True),
    sa.Column('two_factor_backup_codes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('password_reset_token', sa.Text(), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_password_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('lock_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('broker_name', sa.String(length=255), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('account_all_time_stats',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('missed_trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_win', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_loss', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_rr', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('best_win', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('worst_loss', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_trade_duration', sa.String(length=20), nullable=False),
    sa.Column('avg_win_streak', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_win_streak', sa.Integer(), nullable=False),
    sa.Column('avg_loss_streak', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_loss_streak', sa.Integer(), nullable=False),
    sa.Column('recovery_factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_volume', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_commission', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('zella_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('win_rate_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('profit_factor_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_win_loss_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recovery_factor_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_drawdown_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('account_daily_stats',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('missed_trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_win', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_loss', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_rr', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('best_win', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('worst_loss', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_trade_duration', sa.String(length=20), nullable=False),
    sa.Column('avg_win_streak', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_win_streak', sa.Integer(), nullable=False),
    sa.Column('avg_loss_streak', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_loss_streak', sa.Integer(), nullable=False),
    sa.Column('recovery_factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_volume', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_commission', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('zella_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('win_rate_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('profit_factor_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_win_loss_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recovery_factor_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_drawdown_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('trade_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_daily_stats_account_id'), 'account_daily_stats', ['account_id'], unique=False)
    op.create_index('ix_daily_stats_account_date', 'account_daily_stats', ['account_id', 'date'], unique=True)
    op.create_table('account_monthly_stats',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('missed_trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_win', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_loss', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_rr', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('best_win', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('worst_loss', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_trade_duration', sa.String(length=20), nullable=False),
    sa.Column('avg_win_streak', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_win_streak', sa.Integer(), nullable=False),
    sa.Column('avg_loss_streak', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_loss_streak', sa.Integer(), nullable=False),
    sa.Column('recovery_factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_volume', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_commission', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('zella_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('win_rate_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('profit_factor_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_win_loss_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recovery_factor_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_drawdown_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('trade_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_monthly_stats_account_id'), 'account_monthly_stats', ['account_id'], unique=False)
    op.create_index('ix_monthly_stats_account_month', 'account_monthly_stats', ['account_id', 'month'], unique=True)
    op.create_table('ai_insights',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_account_id'), 'ai_insights', ['account_id'], unique=False)
    op.create_table('comments_daily_summary',
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'date')
    )
    op.create_table('comments_monthly_summary',
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'month')
    )
    op.create_table('daily_session_stats',
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('session_name', sa.String(length=50), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('trade_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'date', 'session_name')
    )
    op.create_table('files',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_account_id'), 'files', ['account_id'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_account_id'), 'folders', ['account_id'], unique=False)
    op.create_table('monthly_session_stats',
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('session_name', sa.String(length=50), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'month', 'session_name')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_account_id'), 'notifications', ['account_id'], unique=False)
    op.create_table('pnl_by_day_of_week',
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'day_of_week')
    )
    op.create_table('pnl_by_time_held',
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('duration_range', sa.String(length=20), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'duration_range')
    )
    op.create_table('pnl_by_time_interval',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('interval_start', sa.Time(), nullable=False),
    sa.Column('interval_end', sa.Time(), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pnl_by_time_interval_account_id'), 'pnl_by_time_interval', ['account_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_rules', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('exit_rules', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('risk_rules', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_account_id'), 'strategies', ['account_id'], unique=False)
    op.create_table('streak_records',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('current_win_streak', sa.Integer(), nullable=False),
    sa.Column('max_win_streak', sa.Integer(), nullable=False),
    sa.Column('current_loss_streak', sa.Integer(), nullable=False),
    sa.Column('max_loss_streak', sa.Integer(), nullable=False),
    sa.Column('average_win_streak', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('average_loss_streak', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streak_records_account_id'), 'streak_records', ['account_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(length=35), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('commission', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('swap', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('trade_type', sa.String(length=50), nullable=True),
    sa.Column('execution_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('setups', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('general_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('exit_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('process_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_account_executed_at', 'trades', ['account_id', 'executed_at'], unique=False)
    op.create_index(op.f('ix_trades_account_id'), 'trades', ['account_id'], unique=False)
    op.create_index(op.f('ix_trades_executed_at'), 'trades', ['executed_at'], unique=False)
    op.create_table('trading_sessions',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_sessions_account_id'), 'trading_sessions', ['account_id'], unique=False)
    op.create_table('weekly_stats',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('trade_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_stats_account_id'), 'weekly_stats', ['account_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('trade_id', sa.String(length=35), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(length=30), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_account_id'), 'comments', ['account_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('folder_id', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_account_id'), 'notes', ['account_id'], unique=False)
    op.create_table('strategy_all_time_stats',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('strategy_id', sa.String(length=30), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('expectancy', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_all_time_stats_account_id'), 'strategy_all_time_stats', ['account_id'], unique=False)
    op.create_table('strategy_daily_stats',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('strategy_id', sa.String(length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('expectancy', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('trade_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_daily_stats_account_id'), 'strategy_daily_stats', ['account_id'], unique=False)
    op.create_index(op.f('ix_strategy_daily_stats_strategy_id'), 'strategy_daily_stats', ['strategy_id'], unique=False)
    op.create_table('strategy_monthly_stats',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('strategy_id', sa.String(length=30), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('expectancy', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('trade_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_monthly_stats_account_id'), 'strategy_monthly_stats', ['account_id'], unique=False)
    op.create_index(op.f('ix_strategy_monthly_stats_strategy_id'), 'strategy_monthly_stats', ['strategy_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('strategy_id', sa.String(length=30), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_account_id'), 'tags', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_account_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_strategy_monthly_stats_strategy_id'), table_name='strategy_monthly_stats')
    op.drop_index(op.f('ix_strategy_monthly_stats_account_id'), table_name='strategy_monthly_stats')
    op.drop_table('strategy_monthly_stats')
    op.drop_index(op.f('ix_strategy_daily_stats_strategy_id'), table_name='strategy_daily_stats')
    op.drop_index(op.f('ix_strategy_daily_stats_account_id'), table_name='strategy_daily_stats')
    op.drop_table('strategy_daily_stats')
    op.drop_index(op.f('ix_strategy_all_time_stats_account_id'), table_name='strategy_all_time_stats')
    op.drop_table('strategy_all_time_stats')
    op.drop_index(op.f('ix_notes_account_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_account_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_weekly_stats_account_id'), table_name='weekly_stats')
    op.drop_table('weekly_stats')
    op.drop_index(op.f('ix_trading_sessions_account_id'), table_name='trading_sessions')
    op.drop_table('trading_sessions')
    op.drop_index(op.f('ix_trades_executed_at'), table_name='trades')
    op.drop_index(op.f('ix_trades_account_id'), table_name='trades')
    op.drop_index('ix_trades_account_executed_at', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_streak_records_account_id'), table_name='streak_records')
    op.drop_table('streak_records')
    op.drop_index(op.f('ix_strategies_account_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_pnl_by_time_interval_account_id'), table_name='pnl_by_time_interval')
    op.drop_table('pnl_by_time_interval')
    op.drop_table('pnl_by_time_held')
    op.drop_table('pnl_by_day_of_week')
    op.drop_index(op.f('ix_notifications_account_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('monthly_session_stats')
    op.drop_index(op.f('ix_folders_account_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_files_account_id'), table_name='files')
    op.drop_table('files')
    op.drop_table('daily_session_stats')
    op.drop_table('comments_monthly_summary')
    op.drop_table('comments_daily_summary')
    op.drop_index(op.f('ix_ai_insights_account_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index('ix_monthly_stats_account_month', table_name='account_monthly_stats')
    op.drop_index(op.f('ix_account_monthly_stats_account_id'), table_name='account_monthly_stats')
    op.drop_table('account_monthly_stats')
    op.drop_index('ix_daily_stats_account_date', table_name='account_daily_stats')
    op.drop_index(op.f('ix_account_daily_stats_account_id'), table_name='account_daily_stats')
    op.drop_table('account_daily_stats')
    op.drop_table('account_all_time_stats')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('background_jobs')
    # ### end Alembic commands ###
