"""Add closed_at and close_time to trades

Revision ID: caf17a19d7ed
Revises: 72910f01539a
Create Date: 2026-02-23 11:12:43.065564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf17a19d7ed'
down_revision: Union[str, Sequence[str], None] = '72910f01539a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trades', sa.Column('close_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'close_time')
    op.drop_column('trades', 'closed_at')
    # ### end Alembic commands ###
